INSERT INTO QUESTION(ID, QUESTION ) VALUES (1,'Do you enjoy working in a team?');
INSERT INTO MULTIPLE_OPTION (ID ,DESCRIPTION ,OPTION_VALUE ,POINTS ,QUESTION_ID ) VALUES(1,'Teamwork is in my blood','A',5,'1');
INSERT INTO MULTIPLE_OPTION (ID ,DESCRIPTION ,OPTION_VALUE ,POINTS ,QUESTION_ID ) VALUES(2,'Yes, I do','B',3,'1');
INSERT INTO MULTIPLE_OPTION (ID ,DESCRIPTION ,OPTION_VALUE ,POINTS ,QUESTION_ID ) VALUES(3,' I prefer to work alone','C',0,'1');

INSERT INTO QUESTION(ID, QUESTION ) VALUES (2,'How long have you been working with Java?');
INSERT INTO MULTIPLE_OPTION (ID ,DESCRIPTION ,OPTION_VALUE ,POINTS ,QUESTION_ID ) VALUES(4,' Never ','A',0,'2');
INSERT INTO MULTIPLE_OPTION (ID ,DESCRIPTION ,OPTION_VALUE ,POINTS ,QUESTION_ID ) VALUES(5,' Less than 1 year ','B',1,'2');
INSERT INTO MULTIPLE_OPTION (ID ,DESCRIPTION ,OPTION_VALUE ,POINTS ,QUESTION_ID ) VALUES(6,' Less than 2 year ','C',3,'2');
INSERT INTO MULTIPLE_OPTION (ID ,DESCRIPTION ,OPTION_VALUE ,POINTS ,QUESTION_ID ) VALUES(7,' Less than 3 year ','D',5,'2');

INSERT INTO QUESTION(ID, QUESTION ) VALUES (3,'How do you feel about automated tests?');
INSERT INTO MULTIPLE_OPTION (ID ,DESCRIPTION ,OPTION_VALUE ,POINTS ,QUESTION_ID ) VALUES(8,' Mandatory  ','A',3,'3');
INSERT INTO MULTIPLE_OPTION (ID ,DESCRIPTION ,OPTION_VALUE ,POINTS ,QUESTION_ID ) VALUES(9,' Waste of time  ','B',0,'3');

INSERT INTO POINTS_EVALUATION (ID ,MIN_POINTS , MAX_POINTS ,MESSAGE) VALUES(1, 0, 6, 'Unfortunately, we don’t match!');
INSERT INTO POINTS_EVALUATION (ID ,MIN_POINTS , MAX_POINTS ,MESSAGE) VALUES(2, 7, 10, 'That looks good!');
INSERT INTO POINTS_EVALUATION (ID ,MIN_POINTS , MAX_POINTS ,MESSAGE) VALUES(3, 11, null, 'Excellent!');